"""Email delivery for GEO reports via SendGrid."""

import base64
import os
from app.config import get_settings

settings = get_settings()


def send_report_email(to_email: str, brand_name: str, geo_score: int, pdf_path: str, download_url: str):
    """Send the GEO report PDF to the customer via email."""
    try:
        from sendgrid import SendGridAPIClient
        from sendgrid.helpers.mail import (
            Mail, Attachment, FileContent, FileName, FileType, Disposition
        )
    except ImportError:
        print("SendGrid not installed. Skipping email delivery.")
        return False

    if not settings.sendgrid_api_key:
        print("No SendGrid API key configured. Skipping email delivery.")
        return False

    # Read PDF attachment
    with open(pdf_path, "rb") as f:
        pdf_data = base64.b64encode(f.read()).decode()

    message = Mail(
        from_email=settings.from_email,
        to_emails=to_email,
        subject=f"Your GEO Report is Ready — {brand_name} scored {geo_score}/100",
        html_content=f"""
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h1 style="color: #1a1a2e;">Your GEO Report is Ready</h1>

            <div style="background: #f8f9fa; border-radius: 12px; padding: 24px; text-align: center; margin: 20px 0;">
                <p style="color: #666; margin: 0;">Overall GEO Score</p>
                <h2 style="color: {'#00b894' if geo_score >= 80 else '#0f3460' if geo_score >= 60 else '#fdcb6e' if geo_score >= 40 else '#d63031'}; font-size: 48px; margin: 8px 0;">{geo_score}/100</h2>
                <p style="color: #666;">{brand_name}</p>
            </div>

            <p>Your comprehensive Generative Engine Optimization (GEO) report is attached to this email as a PDF.</p>

            <p>The report includes:</p>
            <ul>
                <li>AI Citability & Visibility scoring</li>
                <li>Brand Authority analysis across AI-cited platforms</li>
                <li>Content E-E-A-T assessment</li>
                <li>Technical GEO infrastructure audit</li>
                <li>Schema & structured data evaluation</li>
                <li>Prioritized 30-day action plan</li>
            </ul>

            <p>
                <a href="{download_url}" style="display: inline-block; background: #0f3460; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px;">
                    Download Report
                </a>
            </p>

            <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0;" />
            <p style="color: #999; font-size: 12px;">
                This report was generated by GEO Score — AI Search Visibility Analysis.
            </p>
        </div>
        """,
    )

    attachment = Attachment(
        FileContent(pdf_data),
        FileName(f"GEO-Report-{brand_name.replace(' ', '-')}.pdf"),
        FileType("application/pdf"),
        Disposition("attachment"),
    )
    message.attachment = attachment

    try:
        sg = SendGridAPIClient(settings.sendgrid_api_key)
        sg.send(message)
        return True
    except Exception as e:
        print(f"Email send failed: {e}")
        return False
